"""Add DocumentCategory model and update Document model

Revision ID: 04144a64704d
Revises: eeadc9b5d908
Create Date: 2025-03-02 22:58:05.245877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04144a64704d'
down_revision = 'eeadc9b5d908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_document_category', 'document_category', ['category_id'], ['id'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('fk_document_category', type_='foreignkey')
        batch_op.drop_column('category_id')

    op.drop_table('document_category')
    # ### end Alembic commands ###
