"""Add Material and Color models

Revision ID: 07947181706c
Revises: 244f9ed119cd
Create Date: 2025-03-02 19:24:47.076486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07947181706c'
down_revision = '244f9ed119cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material')
    op.drop_table('color')
    # ### end Alembic commands ###
