"""Add location table and update item table

Revision ID: 530acaf7ceae
Revises: e581bc5e3c53
Create Date: 2025-03-03 16:58:19.706476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530acaf7ceae'
down_revision = 'e581bc5e3c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_item_location', 'location', ['location_id'], ['id'])
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('fk_item_location', type_='foreignkey')
        batch_op.drop_column('location_id')

    op.drop_table('location')
    # ### end Alembic commands ###
