"""added amterial and color

Revision ID: 688caa2c5e0a
Revises: 
Create Date: 2025-03-01 17:41:13.884042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688caa2c5e0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('color')
        batch_op.drop_column('material')

    # ### end Alembic commands ###
