"""Convert material and color to foreign keys

Revision ID: 89795b579eac
Revises: 07947181706c
Create Date: 2025-03-02 19:29:14.544276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89795b579eac'
down_revision = '07947181706c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('material')
        batch_op.drop_column('color')
        batch_op.add_column(sa.Column('material_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('color_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_item_material', 'material', ['material_id'], ['id'])
        batch_op.create_foreign_key('fk_item_color', 'color', ['color_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('color_id')
        batch_op.drop_column('material_id')

    # ### end Alembic commands ###
