"""Remove tags field from Item model

Revision ID: e581bc5e3c53
Revises: 2bfc560eddde
Create Date: 2025-03-03 12:33:55.737540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e581bc5e3c53'
down_revision = '2bfc560eddde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
