"""Add Category model and update Item model with named constraints

Revision ID: eeadc9b5d908
Revises: 89795b579eac
Create Date: 2025-03-02 22:33:07.989803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeadc9b5d908'
down_revision = '89795b579eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_item_category', 'category', ['category_id'], ['id'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('fk_item_category', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
